[package]
name = "thehermit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
shuttle-serenity = "0.42.0"
shuttle-runtime = "0.42.0"
serenity = { version = "0.11.5", default-features = false, features = [
    "client", "gateway", "rustls_backend", "model","cache","builder","standard_framework","voice"
]}
tokio = "1.26.0"
tracing = "0.1.37"
reqwest = { version = "0.11.22", features = ["json"] }
serde = "1.0.192"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
features = ["yt-dlp"]

